name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3   
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.JFROG_USER }}
        password: ${{ secrets.JFROG_TOKEN }}
        registry: ${{ secrets.JFROG_REPO }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: "finnoctodocker/hello-world:${{github.run_number}}-${{ github.head_ref || github.ref_name }}-${{ github.sha }}"
        
    # Octopus OIDC login
    - name: Login to Octopus Deploy
      uses: OctopusDeploy/login@v1.0.1
      with: 
        server: https://octopus-operations.octopus.app
        service_account_id: ${{ secrets.OCTOPUSSERVICEACCOUNT }}

    # Octopus Build Info
    - name: Push Build Information to Octopus Deploy
      uses: OctopusDeploy/push-build-information-action@v3
      with:
        packages: 
          "finnoctodocker/hello-world"
        version: "${{github.run_number}}-${{ github.head_ref || github.ref_name }}-${{ github.sha }}"
        space: "Finn D"
        overwrite_mode: OverwriteExisting